server:
  port: 0
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/Users/kakao/Documents/work/test/cloud/db/client
    username: user
    password: password
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      formatSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        formatSql: true
        id:
          newGeneratorMappings: true
