server:
  port: 80
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
security:
  oauth2:
    resource:
      id: API
      loadBalanced: true
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----
                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnY5zPuq27q6Q3yV+Dx3S
                  YnjBbahpysKwQCRAn+rZa+0RjHdfgPmgmwA84vlbDLPfBca1Kv8vkcpdjrPuqY1b
                  +2fQph7bIXBr5grGDL7fYy/fmg5GDLvbvfRdsqyb1vIAUZkk/lcxxFeRqk+SMjxd
                  QPcdAerzy1uivQ+mvUi7phewRW0dujsSLdgfgcSIkAZjI2j9UGjkK1rbbXcQp8v8
                  kZZSd/GTciQwssR8cznFtOuduhF2EUy7rlTZsn5X48yrOo3WaHsWI3/Oc7gaTqHe
                  kxNRWZVtBoOoca4k6YWYPwhQSARMPVLVcs7OsKwhtknYiA+CUcg1cwrksxxbvIMV
                  6wIDAQAB
                  -----END PUBLIC KEY-----
