server:
  port: 80
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

